/* eslint-disable no-console */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { compilePack } from '@foundryvtt/foundryvtt-cli';
import { build as esbuild } from 'esbuild';

/**
 * Authors the shipped "Splash Presets" compendium. The tumbler lock's structure lives only in
 * `src/behaviors/tumblerLock.ts`; this calls its `build()`, rewrites the random ids to stable readable
 * ones for clean git diffs, and compiles a LevelDB pack the module declares in `packs[]`.
 *
 * Source JSON is committed under `src/packs/splash-presets/`; the compiled LevelDB under `packs/` is a
 * gitignored build artifact regenerated by `yarn build:packs`.
 */

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/** Bundles the behavior to a temp ESM module with esbuild, so CI's older Node need not import `.ts` natively. */
async function loadTumblerLock() {
	const tmp = path.join(root, 'tools/.preset-build.tmp.mjs');
	await esbuild({
		entryPoints: [path.join(root, 'src/behaviors/tumblerLock.ts')],
		bundle: true,
		platform: 'node',
		format: 'esm',
		outfile: tmp,
	});
	try {
		return (await import(pathToFileURL(tmp).href)).tumblerLock;
	} finally {
		fs.rmSync(tmp, { force: true });
	}
}
const srcDir = path.join(root, 'src/packs/splash-presets');
const outDir = path.join(root, 'packs/splash-presets');

// Fixed Foundry document ids so the pack's uuids never churn between builds.
const JOURNAL_ID = 'splashPresetJrnl';
const TUMBLER_PAGE_ID = 'splashTumblerPg0';

/** Derives a suffix from the object's name so ids read as `wheel0-middle`, `unlock`. */
function roleSuffix(name) {
	return String(name ?? 'part').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'part';
}

/**
 * Rewrites build()'s random ids to stable readable ones, also remapping cross-references carried in
 * `context` (the Unlock button's `Wheels` list), mirroring what the editor's `applySpriteGroupPreset` does.
 */
function stabilizeIds(sprites) {
	const groupMap = {};
	let g = 0;
	for (const s of sprites) {
		if (s.groupId && !(s.groupId in groupMap)) groupMap[s.groupId] = `wheel${g++}`;
	}
	const remapRef = v => (typeof v === 'string' && groupMap[v]) ? groupMap[v] : v;
	const usedIds = new Set();
	return sprites.map((s) => {
		const copy = structuredClone(s);
		copy.groupId = copy.groupId ? groupMap[copy.groupId] : copy.groupId;
		const base = copy.groupId ? `${copy.groupId}-${roleSuffix(copy.name)}` : roleSuffix(copy.name);
		let id = base;
		for (let i = 2; usedIds.has(id); i++) id = `${base}-${i}`;
		usedIds.add(id);
		copy.id = id;
		if (copy.context && typeof copy.context === 'object') {
			for (const [k, v] of Object.entries(copy.context)) {
				copy.context[k] = Array.isArray(v) ? v.map(remapRef) : remapRef(v);
			}
		}
		return copy;
	});
}

function buildTumblerPage(tumblerLock) {
	const sprites = stabilizeIds(tumblerLock.build({ codeword: 'OPEN' }, { stateKey: 'preset' }));
	return {
		_id: TUMBLER_PAGE_ID,
		_key: `!journal.pages!${JOURNAL_ID}.${TUMBLER_PAGE_ID}`,
		name: 'Tumbler Lock',
		type: 'splash.preset',
		title: { show: false, level: 1 },
		system: {
			notes: 'A combination lock. Drop it onto a splash and it asks for the code word, generating one '
				+ 'wheel per letter plus an Unlock button. The baked sprites below are a 4-wheel "OPEN" preview.',
			// Behavior-backed: applying re-runs the tumbler-lock dialog and build rather than stamping these sprites.
			behavior: 'tumbler-lock',
			payload: { type: 'spriteGroup', value: sprites },
		},
	};
}

function buildJournal(tumblerLock) {
	return {
		_id: JOURNAL_ID,
		_key: `!journal!${JOURNAL_ID}`,
		name: 'Tumbler Lock',
		pages: [buildTumblerPage(tumblerLock)],
		ownership: { default: 2 },
	};
}

async function main() {
	const tumblerLock = await loadTumblerLock();
	fs.rmSync(srcDir, { recursive: true, force: true });
	fs.mkdirSync(srcDir, { recursive: true });
	fs.rmSync(outDir, { recursive: true, force: true });
	fs.mkdirSync(outDir, { recursive: true });

	const journal = buildJournal(tumblerLock);
	const file = path.join(srcDir, 'tumbler-lock.json');
	fs.writeFileSync(file, `${JSON.stringify(journal, null, '\t')}\n`);
	console.log(`Wrote source ${path.relative(root, file)} (${journal.pages[0].system.payload.value.length} sprites)`);

	await compilePack(srcDir, outDir, { log: true });
	console.log(`Compiled pack → ${path.relative(root, outDir)}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
